version: '3.8'

services:
  url-shortner:
    container_name: url-shortener-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/url_shortener?schema=public
    volumes:
      - .:/usr/src/app
    command: npm run dev
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: url_shortener_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: url_shortener
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
  